# Multi-stage Containerfile: golang:1.26.5-alpine builder → distroless:nonroot final.
# Builds with --network=none using hermeto-prefetched dependencies.
# Supports linux/amd64 and linux/arm64.

# Go 1.26.5 Alpine (matched to go.mod's toolchain directive).
# Image: docker.io/library/golang:1.26.5-alpine
# Digest: sha256:0178a641fbb4858c5f1b48e34bdaabe0350a330a1b1149aabd498d0699ff5fb2 (manifest-list for multi-arch)
# Verified 2026-08-02 via registry.hub.docker.com/v2/repositories/library/golang/tags/1.26.5-alpine
# Supports: amd64 (sha256:111d79159b2326f7e80c4a4706e1ba166acb0e2611df853955f3621828cd49e8)
#           arm64 (sha256:787328cefd7937073af18fc4b3a725f47e011ffdde9c2908239a25cae6b2f02b)
FROM docker.io/library/golang@sha256:0178a641fbb4858c5f1b48e34bdaabe0350a330a1b1149aabd498d0699ff5fb2 AS builder

# Hermetic build: no network access; GOTOOLCHAIN must use only what's in the image.
ENV GOTOOLCHAIN=local

# Mount hermeto-prefetched dependencies (injected by CI workflow).
# Buildah: --volume ./hermeto-output:/tmp/hermeto-output:Z
#          --volume ./hermeto.env:/tmp/hermeto.env:Z
# These are provided by the CI job; not available during local podman build.

# Copy source code.
WORKDIR /build
COPY . .

# Source hermeto environment (GOPROXY, GOMODCACHE, etc.) generated by hermeto.
# This is set at build time by CI; local builds without hermeto will fail here.
RUN source /tmp/hermeto.env && \
  go build -o /tmp/readme-builder ./cmd/readme-builder

# Distroless static:nonroot final stage.
# Image: gcr.io/distroless/static-debian13:nonroot
# Digest: sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6 (manifest-list for multi-arch)
# Verified 2026-08-02 via coordinator QA verification
# Supports: amd64 (sha256:23795be0fe67b7d47d1ee62b19c7db750152db627d5bbfa31307e892a7575bec)
#           arm64 (sha256:42ae677c641858a6347005914586184474501cceb30dfecf4a20062b3bc00312)
# Distroless static images are ~2 MiB and include CA certificates, timezone data,
# and nonroot user (UID 65532), with no shell or package manager.
FROM gcr.io/distroless/static-debian13@sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6

# Ship the LICENSE file (GPL-3.0-or-later).
COPY LICENSE /

# Copy the binary from builder.
COPY --from=builder /tmp/readme-builder /readme-builder

# Set OCI image metadata for conveyance compliance (GPLv3).
LABEL org.opencontainers.image.source="https://github.com/Odilhao/readme-builder"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"

# Default entry point: the binary.
ENTRYPOINT ["/readme-builder"]
